services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - mangoberry-net
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - mangoberry-net
    env_file:
      - ./backend/.env
networks:
    mangoberry-net:
      driver: bridge